### PR TITLE
Update IS documentation logo and brand colors

### PR DESCRIPTION
**Pull request by NikkiWines**
Fixes: https://github.com/Expensify/Expensify/issues/170711

## OLD
Screen Shot 2021-07-16 at 1 47 32 PM

Screen Shot 2021-07-16 at 1 48 53 PM

## NEW
Screen Shot 2021-07-19 at 4 20 52 PM

Screen Shot 2021-07-16 at 4 56 49 PM

### CODE REVIEW

**Comment by shawnborton** [comment]
For the top left logo, what if we did something like this instead so it matches things like our Community and Status?
image


image


cc @Expensify/design

**Comment by NikkiWines** [comment]
That's fine by me! If you want to send across the updated logo.png file I can add it to the changes

**Comment by shawnborton** [comment]
Let me know how this looks: [expensify-integration-server.png.zip](https://github.com/Expensify/slate/files/6843954/expensify-integration-server.png.zip)

**Comment by NikkiWines** [comment]
@shawnborton I think the new png file still needs the same padding as the current one
Screen Shot 2021-07-19 at 3 39 28 PM

**Comment by shawnborton** [comment]
Ah okay, try this one: [expensify-integration-server.png.zip](https://github.com/Expensify/slate/files/6844329/expensify-integration-server.png.zip)

**Comment by NikkiWines** [comment]
That looks better, not sure if the top-padding is too large now, but it looks like what we had with the other logo
Screen Shot 2021-07-19 at 4 10 52 PM

**Comment by shawnborton** [comment]
Ah okay... one last try! [expensify-integration-server.png.zip](https://github.com/Expensify/slate/files/6844378/expensify-integration-server.png.zip)

**Comment by NikkiWines** [comment]
Beautiful! 

Screen Shot 2021-07-19 at 4 20 52 PM

**Comment by shawnborton** [comment]
Nice, :shipit:

**Comment by megankelso** [comment]
looks good y'all, thanks for updating

**Review by francoisl — APPROVED** [review]

**Pull request merged**
